### ISSUE TITLE
Information about caches

### ISSUE THREAD

**Issue by garygreen** [bmewburn/intelephense#125]
Hi Ben

Would you be able to describe what these folders are for / doing exactly in Code?

On my machine: 

![image](https://user-images.githubusercontent.com/1702638/37566584-08463a3c-2ab3-11e8-9eac-d38a624f8302.png)

Each folder has thousands of json files  - I assume they are generated and transversed everytime in VS Code to provide InteliSense functionality?

Out of interest:

* Is there a more efficient way to store data from these files, maybe in a proper database or grouping common / certain files so there aren't so many to transverse? I haven't done any benchmarks but I'd imagine going through and decoding 10,000 json files each time would be time consuming?

* Do the files ever get "cleansed" - for example, I have deleted some files in my project yet the various references / json files relating to those files still remain there

* Is it possible to turn off tracking certain files, paths or globs? Some kind of whitelist/blacklist type functionality would be good. For example, there is a package called "aws/aws-sdk-php" which has a [large number of data files](https://github.com/aws/aws-sdk-php/tree/master/src/data) in PHP, these I would never want to have IntelliSense for, so it seems wasteful to scan/generate files for them. 

* As the point above, could files be intelligently scanned to determine if they are something that is likely to be a good / bad candidate for InteliSense? You probably don't want config / json-in-php files added, or anything under the "tests" directory / anything inside the vendors "autoload-dev" mappings.

**Comment by bmewburn** [comment]
Hi @garygreen , the json files are cached symbol and reference information from the workspace. They are not usually created each time vscode starts up but rather on the first time the workspace is opened. Symbol files are read on each startup to load symbol info into memory. References files are read on demand.

> Is there a more efficient way to store data from these files
Possibly, though a lot of the startup time is spent rebuilding the symbol index which is not cached atm. I'm considering using levelup to cache data.

> Do the files ever get "cleansed"
File watcher events are handled, and file mod times are checked on startup. Cached data should be getting removed if files are deleted.

> Is it possible to turn off tracking certain files, paths or globs?
You can use the vscode `files.exclude` setting

> could files be intelligently scanned to determine if they are something that is likely to be a good / bad candidate for InteliSense? 
Some default excludes could probably be added. I'm open to any suggestions on how to improve this. For now user's are responsible for what files in the workspace should be indexed.

**Comment by garygreen** [comment]
>  Symbol files are read on each startup to load symbol info into memory. 

Is it possible to turn this off? I assume these are used when doing the Symbol palette (CTRL + SHIFT + O)? Personally I barely use that feature so the thought of 10,000 json files being thrashed on SSD for a feature that's barely used makes me anxious 🐧 
Alternatively, maybe the symbol information could be read on demand for when you actually go to open the palette, or am I misunderstanding what this feature is used for?

> Possibly, though a lot of the startup time is spent rebuilding the symbol index which is not cached atm. I'm considering using levelup to cache data.

That's great, levelup looks very interesting. Does VS Code not use it's own database engine of some kind? Surprised there isn't a standard database / query language used for plugins. As Levelup is a key-value store rather than JSON, how would you envisage the storage of the keys, would they just be compressed down in "dot" format?

> You can use the vscode files.exclude setting

This isn't quite what I was looking for. I've never really been much a fan of the `files.exclude` option in VS Code because it's usage is mixed - for example it's used to determine what files are visible in the sidebar tree - I want ALL `vendor` to be visible always in the sidebar, however I sometimes don't want certain vendors to appear when searching CTRL + P, etc. So Intelephense could use this option but it's not ideal, should really have custom options like `intelephense.excludeFiles`.

**Comment by bmewburn** [comment]
> Is it possible to turn this off?
Unfortunately not, but I have been giving this some thought and I think this caching mechanism can be removed altogether. Parsing and symbol reading is fast enough that the original src files can be read on demand and index cached only. I'm looking at this now as part of the next release.

An `intelephense.excludeFiles` makes sense. There was a similar request in #108 . I'm in the process of moving the workspace scanning out of the vscode client and into the server so this can form part of that work. VSCode `files.exclude` was chosen at the time because all the file finding/excluding was available via the vscode API.

**Comment by bmewburn** [comment]
There's been some progress. Unfortunately I don't get paid for this so I don't get to work on it as much as I'd like to.

**Comment by garygreen** [comment]
@bmewburn would you be able to point me in the right direction to disable the symbol lookups / json files? Looking to fork and maybe will send a PR. Whenever I launch vscode my hard drive get's thrashed with all the json lookups and it seems to be originating from this extension so if I could disable it that would be great 😄

**Comment by garygreen** [comment]
So only after a few months the size has gone up considerably and all the JSON files are taking up over 2GB of space now.

Something doesn't seem right with this. Are they definitely getting cleaned up? If you could point me in the right direction to disable the symbol group caching I can fork and do this. I assume it'll just be a case of adding a return statement to disable entering into the function altogether

![image](https://user-images.githubusercontent.com/1702638/41745363-9c0af6fa-759e-11e8-8f53-4dd4260aea64.png)

**Comment by garygreen** [comment]
So just an update on this... vscode extension is now using almost **10GB of data!!** nearly half a million JSON files scattered around.

![image](https://user-images.githubusercontent.com/1702638/51145917-2ee7c380-184d-11e9-8945-0ab950a14d34.png)

@bmewburn Is there anyway symbols can be turned off, at least? If you can point me in the right direction of where in the code it can be turned off I can maybe send a PR

**Comment by chanaksha** [comment]
I see that the @garygreen is probably using windows. But as a workaround on linux you may use tmpfs filesystem mounted directory and create a symbolic link to it as 'workspaceStorage'. That works pretty well. Only downside being if there are other plugins storing data to your workspace, that will be wiped out on reboot as well. You could simply try (assuming /run is already tmpfs on systemd linux system)

`~/.config/Code/User $ ln -snf /run/user/$(id -u) workspaceStorage`

Windows has this ability to create RAM disk and mount it via third party tools.

**Comment by chanaksha** [comment]
Alternatively just by enabling compression of NTFS on workspaceStorage would make significant difference as all these files are text files.

**Comment by chanaksha** [comment]
@garygreen  I agree its masking the problem. In part it's known VSCode issue where workspaceStorage becomes stale for unused workspaces -- and no way to figure out the cleanup. [#32461](https://github.com/Microsoft/vscode/issues/32461).

You can use file.exclude setting to exclude files that you do not want to be indexed, so that disk space is saved.

Any (non-trivial) code completion requires indexing and storing data. Not storing anything causes performance issues. Still if you need it, it is achieved by the workaround by effectively storing this index in memory.

It is possible to improve the storage (as @bmewburn  says to use level up cache). You may compare this with [PHP Language Server](https://github.com/felixfbecker/php-language-server) stores it's files in ${Home}/.phpls and tries to reuse the index as much as possible. But still, it stores it for better performance on next load. By the way, PHPLS indexing is too slow compared to intelliphense (and for me I face some other peculiar problems whereas intelliphense shines)

Brief look through intelliphense code suggests me it may be simple enough to figure out a solution. I might try something in my spare time.

**Comment by bmewburn** [comment]
v1.0.0 is out, in which there is only 6 cache files written to disk in a binary format. Closing as I believe this solves the issue.
