### ISSUE TITLE
Interfaces not in autocomplete

### ISSUE THREAD

**Issue by jrseliga** [bmewburn/intelephense#129]
Are interfaces not supported in autocomplete? I've cleared/reloaded the cache, and still do not get them.

**Comment by bmewburn** [comment]
What's the context? Can you provide a code snippet?

**Comment by jrseliga** [comment]
@bmewburn It does appear to work when declaring an `implements`, however interfaces are not included in autocomplete inside of a method on a class for example. With IOC containers passing a string representation of contract to be resolved is common.

```
class Something
{
    public function do()
    {
        return app(Contract::class)->banana();
    }
}
```

**Comment by arturock** [comment]
If I understood correctly, that's framework magic. There's no simple way to know what will be returned by the app function just because the string parameter contains an interface name and assuming an instance implementing that interface would be kinda silly, however what you can do is assign the returned value to a documented variable and/or document your method, that way you will have autocomplete. It would be something like:

```php
class Something
{
    /**
     * @return type
     */
    public function do()
    {
        /** @var Contract $obj */
        $obj = app(Contract::class);

        return $obj->banana();
    }
}
```

**Comment by jrseliga** [comment]
@arturock I'm not referring to what the framework does at execution time.

@bmewburn When I I start typing `Contract` as the argument for the function `app()`. Code is not providing any interfaces in the autocomplete dialog.
