### ISSUE TITLE
Indexing late to complete

### ISSUE THREAD

**Issue by alexandredevserra** [bmewburn/intelephense#58]
Inteliphense indexing is perfect, but make this all the time is bad,
for exemple, I'm use laravel to program and indexing late to complete
if it is possible, make same phpstorm, just indexing once.
I don't know how this works, it's a sugestion.
I think that phpstorm save the indexing in somewhere.

**Comment by Talv** [comment]
What you want is caching. So that the computation doesn't happen again, every time you open the project.

For time duration it is also important to exclude irrevelant php files. Such as cache generated by frameworks, or tests directories from dependencies.

Regarding indexing I must say it is actually remarkably fast!
On a Magento2 code base it takes 25s to complete (with over 20k files). That's on a desktop with i7-7700K and SSD though. I imagine it's considerably slower on a notebook.

I did some comparision by curiosity, with some competitors of `intelephense`. Here are the results:

---

>`bmewburn/intelephense` *current stable*

indexing time: **24.702s** \
caching: No
```r
Indexing ended | 20978 files | 24.702 s
```

>`php-integrator/core` *v2.1.7*

indexing time: **239.788s** \
caching: Yes - uses SQLite db for every piece. Upon loading it only checks for eventual changes in the workspace.
```r
php-integrator-base - Indexing: 239788.405ms
```

>`felixfbecker/php-language-server` *current stable*

indexing time (with cached dependecies): **46s**\
indexing time (w/o cached dependencies): **864s**\
caching: Partly - caches only composer dependencies. Uses PHP serialization, and stores data in text files.

with cache:
```r
All 21794 PHP files parsed in 46 seconds. 1200 MiB allocated.
```
Log message is a bit missguiding - it processed only 4740 files. As most of it were composer dependencies, restored from cache.

without cache:
```r
All 21794 PHP files parsed in 864 seconds. 996 MiB allocated.
```
That was freaking long. It also processed 43586 files. That means it did double-pass.

---

I don't know how it compares to PhpStorm. But that's software from another grade..

Thus with such a great performance I'd rather prioritize other tasks if I was the author.

**Comment by bmewburn** [comment]
I've been looking into this as part of providing find references functionality. Currently a single pass needs to be done over files to get symbol information then this symbol info is cached client side. So there is some caching but the reason it still appears to index every time the extension starts is that it still has to load the cached symbols and rebuild the index. For me the time it takes for this has not been a big deal.

However, to include references I think It's going to need a second pass over all files to get this information and I'm looking at caching all this information server side and also caching the indexes. This should mean that it's going to take twice as long to index the first time but after this the extension should be ready in the small amount of time it needs to read from the cache and load into memory.

**Comment by Talv** [comment]
Wow, I actually did look over your code a bit, but I didn't expect any caching on the client side. I ran the test again after wiping this symbol cache. It went up to **65.967 s**. What is still very good. But as you say, with upcoming impementation of *ReferenceProvider* it will increase.. what is after all inevitable.

**Comment by bmewburn** [comment]
Yeah I guess the cache client side is a bit unexpected. I was trying to avoid any persistence on the server side and have all IO via the language server protocol.

**Comment by bmewburn** [comment]
Some improvements here with v0.8.0. Leaving open for now as this can probably be improved upon further.

**Comment by bmewburn** [comment]
Tracking further improvements in #91
